// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL0I9UxxzVBQJB2Tu3uBoc7RDtHIIWawY',
    appId: '1:196168389204:web:c82257f8d6ff41000e13c1',
    messagingSenderId: '196168389204',
    projectId: 'fir-284f8',
    authDomain: 'fir-284f8.firebaseapp.com',
    storageBucket: 'fir-284f8.firebasestorage.app',
    measurementId: 'G-3Q3YS3Y4MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDebOrzb5YY1OXos-6eM62hZyE4uz8R4EM',
    appId: '1:196168389204:android:fb2d0c351f413e2e0e13c1',
    messagingSenderId: '196168389204',
    projectId: 'fir-284f8',
    storageBucket: 'fir-284f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2HeLeiL3CrOw1ePDRtMIqkZEzxNlDTyc',
    appId: '1:196168389204:ios:68fad18e4228edb20e13c1',
    messagingSenderId: '196168389204',
    projectId: 'fir-284f8',
    storageBucket: 'fir-284f8.firebasestorage.app',
    iosBundleId: 'com.example.agentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2HeLeiL3CrOw1ePDRtMIqkZEzxNlDTyc',
    appId: '1:196168389204:ios:68fad18e4228edb20e13c1',
    messagingSenderId: '196168389204',
    projectId: 'fir-284f8',
    storageBucket: 'fir-284f8.firebasestorage.app',
    iosBundleId: 'com.example.agentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHCvCooxQz8EzBC-jyToklenqhOrrZsOo',
    appId: '1:196168389204:web:35fcd291f44970a90e13c1',
    messagingSenderId: '196168389204',
    projectId: 'fir-284f8',
    authDomain: 'fir-284f8.firebaseapp.com',
    storageBucket: 'fir-284f8.firebasestorage.app',
    measurementId: 'G-JTR0Q0348T',
  );
}
